version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/custom-init.sh:/docker-entrypoint.d/40-custom-init.sh:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./volumes/crates:/var/cache/nginx/crates
      - ./volumes/certs:/etc/letsencrypt:ro
      - ./volumes/certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-10g}
      - NGINX_WAIT=${NGINX_WAIT:-30}
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot
    volumes:
      - ./volumes/certs:/etc/letsencrypt
      - ./volumes/certbot_www:/var/www/certbot
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL=${EMAIL}
      - TOS=${TOS}
    entrypoint: "/bin/sh -c '\
      trap exit TERM; \
      if [ ! -d /etc/letsencrypt/live/$${DOMAIN_NAME} ]; then \
        certbot certonly --non-interactive \
          --webroot -w /var/www/certbot \
          --email $${EMAIL} -d $${DOMAIN_NAME} \
          --rsa-key-size 4096 --force-renewal $${TOS}; \
      fi; \
      while :; do \
        certbot renew; \
        sleep 12h & wait $${!}; \
      done;'"
    depends_on:
      - nginx